#!/usr/bin/env python3
"""Build kylemulleady.com: Markdown posts + Jinja templates -> plain static HTML.

No JavaScript is emitted and no server runs. Code is highlighted at build time by
Pygments, so pages need nothing but HTML and one stylesheet.
"""

import re
import shutil
from datetime import date
from pathlib import Path

import markdown
from jinja2 import Environment, FileSystemLoader, select_autoescape
from pygments.formatters import HtmlFormatter

ROOT = Path(__file__).parent
CONTENT = ROOT / "content" / "posts"
TEMPLATES = ROOT / "templates"
STATIC = ROOT / "static"
DIST = ROOT / "dist"

# Where the built site lives on the server. Referenced by the generated nginx config.
SERVER_ROOT = "/var/www/kylemulleady.com"

SITE = {
    "title": "Kyle Mulleady",
    "url": "https://kylemulleady.com",
    "email": "kyle@kylemulleady.com",
    "github": "https://github.com/mulleady1",
}

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n(.*)\Z", re.DOTALL)


def parse_post(path: Path) -> dict:
    """Split a post file into its frontmatter fields and rendered body."""
    raw = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(raw)
    if not match:
        raise ValueError(f"{path.name}: missing frontmatter block")

    meta = {}
    for line in match.group(1).splitlines():
        if not line.strip():
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip().strip('"')

    md = markdown.Markdown(
        extensions=["fenced_code", "codehilite", "tables", "attr_list", "smarty"],
        extension_configs={"codehilite": {"guess_lang": False, "linenums": False}},
    )
    body_md = match.group(2).strip()
    post = dict(meta)
    post["html"] = md.convert(body_md)
    post["date"] = date.fromisoformat(meta["date"])
    post["legacy_id"] = int(meta["legacy_id"]) if "legacy_id" in meta else None
    post["url"] = f"/blog/{meta['slug']}/"
    post["excerpt"] = make_excerpt(body_md)
    return post


def make_excerpt(body_md: str, limit: int = 180) -> str:
    """First paragraph of a post, stripped to plain text for the index page."""
    first = body_md.split("\n\n", 1)[0]
    text = re.sub(r"[*_`#\[\]]|\(https?://[^)]*\)", "", first).strip()
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0] + "…"


def pygments_css() -> str:
    """Syntax highlighting for both colour schemes.

    Pygments styles are built for one background, so a light style on the dark palette
    leaves code barely readable. Emit a light style by default and swap the whole set
    under ``prefers-color-scheme: dark``.

    Only rules scoped to ``.codehilite`` are kept. Pygments also emits a bare
    ``pre { line-height: 125% }``, which would override the block styling in style.css,
    and several line-number rules that are unused because highlighting runs with
    ``linenums`` off. The style's own ``.codehilite`` background rule goes too, so the
    block keeps the surface colour from the palette.
    """

    def defs(style: str, indent: str = "") -> str:
        raw = HtmlFormatter(style=style).get_style_defs(".codehilite")
        lines = [
            ln
            for ln in raw.splitlines()
            if ln.startswith(".codehilite ") and not ln.startswith(".codehilite {")
        ]
        return "\n".join(indent + ln for ln in lines)

    return (
        "/* generated by build.py - do not edit */\n\n"
        + defs("friendly")
        + "\n\n@media (prefers-color-scheme: dark) {\n"
        + defs("native", indent="  ")
        + "\n}\n"
    )


def write_nginx_conf(posts: list[dict]) -> None:
    """Generate the nginx server block, including redirects from the 2016 URLs.

    The old site addressed posts by database id (``/blog/12``). Those ids live on in each
    post's ``legacy_id`` frontmatter, so the redirect list is generated from the content
    rather than maintained by hand and drifting out of step with it.
    """
    redirects = sorted(
        ((p["legacy_id"], p["url"]) for p in posts if p["legacy_id"]),
        key=lambda pair: pair[0],
    )
    lines = "\n".join(
        f"    location = /blog/{old} {{ return 301 {new}; }}" for old, new in redirects
    )

    conf = f"""# Generated by build.py. Install with deploy/install-server.sh.
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name kylemulleady.com www.kylemulleady.com;

    root {SERVER_ROOT};
    index index.html;

    access_log /var/log/kylemulleady.com/access.log;
    error_log  /var/log/kylemulleady.com/error.log;

    ssl_certificate     /etc/letsencrypt/live/kylemulleady.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kylemulleady.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    # Static HTML with no scripts of any kind, so the policy can be absolute.
    add_header Content-Security-Policy "default-src 'self'; script-src 'none'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'" always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Posts moved from /blog/<id> to /blog/<slug>/ in the 2026 rebuild.
{lines}

    # The two 2016 stubs were not republished.
    location = /blog/4  {{ return 301 /blog/; }}
    location = /blog/13 {{ return 301 /blog/; }}

    # /login, /contact and the whole /api surface belonged to the retired .NET app.
    location = /login   {{ return 301 /; }}
    location = /contact {{ return 301 /; }}
    location /api       {{ return 410; }}

    location /css    {{ expires 7d; add_header Cache-Control "public"; }}
    location /images {{ expires 30d; add_header Cache-Control "public"; }}

    location / {{
        try_files $uri $uri/ $uri.html =404;
    }}

    error_page 404 /404.html;
}}

server {{
    listen 80;
    listen [::]:80;
    server_name kylemulleady.com www.kylemulleady.com;
    return 301 https://kylemulleady.com$request_uri;
}}

server {{
    listen 443 ssl;
    server_name www.kylemulleady.com;
    ssl_certificate     /etc/letsencrypt/live/kylemulleady.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kylemulleady.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    return 301 https://kylemulleady.com$request_uri;
}}
"""
    out = ROOT / "deploy" / "kylemulleady.com.nginx"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(conf, encoding="utf-8")


def write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")


def main() -> None:
    posts = sorted(
        (parse_post(p) for p in CONTENT.glob("*.md")),
        key=lambda p: p["date"],
        reverse=True,
    )

    env = Environment(
        loader=FileSystemLoader(TEMPLATES),
        autoescape=select_autoescape(["html"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["longdate"] = lambda d: d.strftime("%B %-d, %Y")

    if DIST.exists():
        shutil.rmtree(DIST)
    shutil.copytree(STATIC, DIST)

    write(DIST / "css" / "pygments.css", pygments_css())

    write(DIST / "index.html", env.get_template("index.html").render(site=SITE, posts=posts[:3]))
    write(DIST / "blog" / "index.html", env.get_template("blog_list.html").render(site=SITE, posts=posts))
    for post in posts:
        html = env.get_template("post.html").render(site=SITE, post=post)
        write(DIST / "blog" / post["slug"] / "index.html", html)

    write(DIST / "404.html", env.get_template("404.html").render(site=SITE))
    write_nginx_conf(posts)

    print(f"built {len(posts)} posts -> {DIST}")
    for p in posts:
        print(f"  {p['date']}  {p['url']}")


if __name__ == "__main__":
    main()
